### ISSUE TITLE
Potential windows difference

### ISSUE THREAD

**Issue by Elyx0** [tintinweb/solidity-shell#15]
I retried on windows 
node v16.13.2
npm 8.5.4
`npm install -g solidity-shell ganache-cli`

starting `solidity-shell` was giving:
```
🚀 Entering interactive Solidity ^0.8.11 shell. '.help' and '.exit' are your friends.
 »  ℹ️  ganache-mgr: starting temp. ganache instance ...
 »

 🧨 Unable to launch blockchain serivce: ➜ ℹ️  Error: spawn ganache-cli ENOENT

    Please verify that 'ganache-cli' (or similar service) is installed and available in your PATH.
    Otherwise, you can disable autostart by setting 'autostartGanache' to false in your settings or configure a different service and
 '.restartblockchain'.
```

I had to `npm install -g ganache` and `ganache` running in one terminal before starting `solidity-shell` in another. Cheers

**Comment by tintinweb** [comment]
mhm, I'd actually like to avoid having to bundle ganache with solidity shell but I guess at one point convenience wins over pot. unnecessary slack & install size.

the specific error happens because `ganache-cli` was not registered with the windows shell, i.e. `ganache-cli` is not in windows `PATH`. you can confirm this by opening `cmd` and typing `ganache-cli` which should throw an error. There might not be an easy way to figure out the `ganache-cli` path programmatically but I'll try to figure this out. As a hotfix you can always configure a custom `ganache-cli` location in the config but I get that the experience is not the best for first-time users.

I need to think about this one :) I'll keep it open for now. thanks for reporting this 🙌

**Comment by prestance1** [comment]
Been having the same issues and used WSL instead and works fine now. Probably a better alternative than separately running ganache on a different terminal.

**Comment by Elyx0** [comment]
I like to avoid WSL/wsl2 if I can but thanks for adding to the thread

**Comment by 0xsomnus** [comment]
Could spin up a VM too but that's annoying as all hell as I remember from my days using kali.

**Comment by tintinweb** [comment]
As a workaround, did you try changing the `ganacheCmd` setting to point to the absolute path of your ganache installation?
<img width="537" alt="image" src="https://user-images.githubusercontent.com/2865694/162714755-ed34443b-adfc-4ca4-be13-336466287162.png">

I guess it's time to look into how to bundle ganache with `solidity-shell` and make this less cumbersome.
